server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: CUSTOMER-WS
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-service
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate: debug

