server:
  port: 8081
spring:
  application:
    name: CUSTOMER-WS
  datasource:
    password: Fill this later
    url: Fill this later
    username: Fill this later
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect

