server:
  port: ${PORT:0}
spring:
  application:
    name: CUSTOMER-WS
  datasource:
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
