server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: CUSTOMER-WS
  datasource:
    url:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect


